backend:
  name: git-gateway
  branch: main
  repo: amfkut/kven   # üëâ —Ç–≤–æ–π —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π
  base_url: https://api.netlify.com  # –µ—Å–ª–∏ –∏—Å–ø–æ–ª—å–∑—É–µ—à—å Netlify Identity
  auth_endpoint: /api/auth  # –Ω–µ —Ç—Ä–æ–≥–∞–π, –µ—Å–ª–∏ –Ω–µ –∑–Ω–∞–µ—à—å –∑–∞—á–µ–º

media_folder: "images"
public_folder: "/images"

collections:
  - name: homepage
    label: –ì–ª–∞–≤–Ω–∞—è
    files:
      - name: hero
        label: –ë–∞–Ω–Ω–µ—Ä
        file: content/hero.json
        fields:
          - { label: –ó–∞–≥–æ–ª–æ–≤–æ–∫, name: "title", widget: "string" }
          - { label: –ü–æ–¥–∑–∞–≥–æ–ª–æ–≤–æ–∫, name: "subtitle", widget: "text" }
          - { label: –ò–∑–æ–±—Ä–∞–∂–µ–Ω–∏–µ —Ñ–æ–Ω–∞, name: "image", widget: "image" }
