backend:
  name: git-gateway
  # repo: amfkut/kven  # например: username/my-site
  branch: main  # или master

media_folder: "images"  # куда загружать изображения
public_folder: "/images"  # путь для ссылок

collections:
  - name: homepage
    label: Главная
    files:
      - name: hero
        label: Баннер
        file: content/hero.json
        fields:
          - { label: Заголовок, name: "title", widget: "string" }
          - { label: Подзаголовок, name: "subtitle", widget: "text" }
          - { label: Изображение фона, name: "image", widget: "image" }
