backend:
  name: github
  repo: amfkut/kven
  branch: main
  auth_type: implicit

media_folder: "images"
public_folder: "/images"

collections:
  - name: homepage
    label: Главная
    files:
      - name: hero
        label: Баннер
        file: content/hero.json
        fields:
          - { label: Заголовок, name: "title", widget: "string" }
          - { label: Подзаголовок, name: "subtitle", widget: "text" }
          - { label: Изображение фона, name: "image", widget: "image" }
