CMS.init({
  config: {
    backend: {
      name: "github",
      repo: "amfkut/kven", // üëâ —Ç–≤–æ–π —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π
      branch: "main",
    },

    media_folder: "images",
    public_folder: "/images",

collections:
  - name: homepage
    label: –ì–ª–∞–≤–Ω–∞—è
    files:
      - name: hero
        label: –ë–∞–Ω–Ω–µ—Ä
        file: content/hero.json
        fields:
          - { label: –ó–∞–≥–æ–ª–æ–≤–æ–∫, name: "title", widget: "string" }
          - { label: –ü–æ–¥–∑–∞–≥–æ–ª–æ–≤–æ–∫, name: "subtitle", widget: "text" }
          - { label: –ò–∑–æ–±—Ä–∞–∂–µ–Ω–∏–µ —Ñ–æ–Ω–∞, name: "image", widget: "image" }
            ]
          }
        ]
      }
    ]
  }
});
