backend:
  name: git-gateway
  repo: amfkut/kven
  branch: main  # или master

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - name: "homepage"
        label: "Главная"
        file: "content/home.md"
        fields:
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Текст", name: "body", widget: "markdown"}
